### ISSUE TITLE
Questions about the SMILES of hit1, hit2, hit3 mentioned in the paper

### ISSUE THREAD

**Issue by Listen-lei** [huankoh/PSICHIC#10]

**Comment by Listen-lei** [comment]
Regarding the SMILES of hit1 hit2 hit3 mentioned in the paper, can you give me a guide on how to get them, I didn't find the relevant content in the paper, so I can't reproduce the content of the position, this is very confusing, can you give me some help?

**Comment by huankoh** [comment]
Hi Listen-lei, 
Thank you for your question! While we understand the interest in accessing the SMILES of hit1, hit2, and hit3, unfortunately, these details, including the MIPS library, are not publicly available due to intellectual property (IP) considerations.
Best,
Huan
