### ISSUE TITLE
Is openfold required?

### ISSUE THREAD

**Issue by amin-sagar** [huankoh/PSICHIC#2]
Hello.
Thanks for this awesome work.
I am facing problems with installing openfold. I trying multiple things but nothing has worked yet. Before I invest more time in finding a solution, I wanted to ask if it is required for PSICHIC? Or is it only required for modelling structures to show in the jupyter notebook?
Best,
Amin.

**Comment by huankoh** [comment]
Hello Amin, 

Thanks!
You're right, openfold is not necessary for PSICHIC unless is only required for modelling structures. I have updated the README to include the packages required for setting up PSICHIC environment.
Best,
Huan

**Comment by amin-sagar** [comment]
Thanks @huankoh
