### ISSUE TITLE
how to see Protein Residue Importance Scores

### ISSUE THREAD

**Issue by MachineGUN001** [huankoh/PSICHIC#6]
hi,

thanks so much for you to provide the wonderful work.

Can you provide a script, code, or notebook to demonstrate how to display the residues of the protein pocket that are most important for binding with ligands, specifically identifying which residues are crucial for the interaction with the ligand?

many thanks

Best,

**Comment by huankoh** [comment]
Hi, 

Our colab notebook has provided example (with code) of how to display the residues of the protein pocket that are most important for binding with ligands. The interpretation of residue importance score is also saved whenever PSICHIC is run into a csv file where each residue will be assigned with an importance score by PSICHIC.

Best,
Huan

**Comment by MachineGUN001** [comment]
hi, huan,

thanks for your kind explanation.

I found the csv file you mentioned in the fold 'interpretation result', which included the importance score of each residue.

best,

**Comment by huankoh** [comment]
Great! Let me know if you have any other questions.
