### ISSUE TITLE
How do I get the checkpoints for the results in your papers?

### ISSUE THREAD

**Issue by viko-3** [huankoh/PSICHIC#7]
Thanks for such a great job.
But I would like to know if checkpoints are provided in order to test the data directly?

**Comment by huankoh** [comment]
Hi Viko, 

Thanks for the kind words. 

Yes, we provided checkpoints in the trained_weights folder. This includes two trained PSICHIC versions: (1) PDBBind v2020 and (2) large-scale dataset for application purposes. With these trained weights, you can use the screening.py file to run any csv files you are interested to test the data directly. A colab notebook is also provided to achieve this easily.

For other checkpoints, you will need to train PSICHIC on the dataset with the training scripts by following the instructions in the README file.

Cheers,
Huan

**Comment by viko-3** [comment]
> Hi Viko,
> 
> Thanks for the kind words.
> 
> Yes, we provided checkpoints in the trained_weights folder. This includes two trained PSICHIC versions: (1) PDBBind v2020 and (2) large-scale dataset for application purposes. With these trained weights, you can use the screening.py file to run any csv files you are interested to test the data directly. A colab notebook is also provided to achieve this easily.
> 
> For other checkpoints, you will need to train PSICHIC on the dataset with the training scripts by following the instructions in the README file.
> 
> Cheers, Huan

Thanks for your prompt reply.

So, If I want evaluate the results in BindingDB or BioSNAP. I need to train PSICHIC by myself?

**Comment by huankoh** [comment]
Yes, that is correct. To achieve this, please see:

(1) **'dataset' folder** where we provided an explanation to obtain CSV files that specify the dataset split, as well as the code that enabled the split.

(2) **model training** the instruction for training PSICHIC is in the README file.

Cheers,
Huan

**Comment by viko-3** [comment]
> Yes, that is correct. To achieve this, please see:
> 
> (1) **'dataset' folder** where we provided an explanation to obtain CSV files that specify the dataset split, as well as the code that enabled the split.
> 
> (2) **model training** the instruction for training PSICHIC is in the README file.
> 
> Cheers, Huan
